pom.xml
to match first column from spdx.org/licenses
=> update license name

ejb/src/main/java/org/wildfly/httpclient/ejb/HttpInvocationHandler.java
The commit here fixes the issue reported at https://issues.jboss.org/browse/WFLY-9573. 
I will submit a separate independent test case to the WildFly repo which reproduces this issue.
=> Fix for WFLY-9573 

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java
JIRA: https://issues.jboss.org/browse/WEJBHTTP-14
=> [WEJBHTTP-14] Host header should include correct port information

common/pom.xml, common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java, common/src/test/java/org/wildfly/httpclient/common/ClientAuthUtils.java, common/src/test/java/org/wildfly/httpclient/common/ClientHostHeaderTestCase.java, common/src/test/java/org/wildfly/httpclient/common/ConnectionPoolTestCase.java, pom.xml
Added tests for host header including port.
Also added dependency for assertj, which allows more nice assertions taking into account context.
=> WEJBHTTP-14 - Host header includes port tests

naming/src/main/java/org/wildfly/httpclient/naming/HttpRootContext.java
https://issues.jboss.org/browse/WEJBHTTP-19
=> [WEJBHTTP-19] added missing privileged block

ejb/src/main/java/org/wildfly/httpclient/ejb/HttpEJBReceiver.java
Issue: https://issues.jboss.org/browse/WEJBHTTP-23
=> [WEJBHTTP-23] EJB contextData not sent back to client in response when using EJB over HTTP

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java
https://issues.jboss.org/browse/WEJBHTTP-26
https://issues.jboss.org/browse/WFLY-12184
The EJB invocation uses the HttpEJBReceiver which receives
authentication configuration from the EJB layer from WFLY.
In case of the transaction calls the transaction manager
does not provide the configuration to the call again.
The ejb call needs to store the auth config data
and then they could be used during txn calls.
=> [WEJBHTTP-26] authentication context to be present for transaction invocation call

common/src/main/java/org/wildfly/httpclient/common/WildflyClientInputStream.java
Jiras: https://issues.jboss.org/browse/WEJBHTTP-31
https://issues.jboss.org/browse/WEJBHTTP-32
=> [WEJBHTTP-31][WEJBHTTP-32] Fix race condition with WildflyClientInputStream

ejb/pom.xml, ejb/src/main/java/org/wildfly/httpclient/ejb/HttpDiscoveryConfigurator.java, pom.xml
We need this class for invocations with dynamic discovery from standalone client
=> [WEJBHTTP-34] EJB over HTTP discovery: add HttpDiscoveryConfigurator

ejb/src/main/java/org/wildfly/httpclient/ejb/HttpEJBDiscoveryProvider.java
@ropalka This fixes the regression in the testsuite. 
OTOH we should decide whether we move the discovery to another branch
(@darranl  FYI)
=> [WEJBHTTP-35] HttpEJBDiscoveryProvider: per-invocation outstandingCount

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java
Jiras: https://issues.redhat.com/browse/WEJBHTTP-30
https://issues.redhat.com/browse/WEJBHTTP-39
1.0 PR: #34
=> [WEJBHTTP-30][WEJBHTTP-39] Make sure session id is handled for affinity on security 401 scenarios

ejb/src/main/java/org/wildfly/httpclient/ejb/EjbHttpClientMessages.java, ejb/src/main/java/org/wildfly/httpclient/ejb/EjbHttpService.java, ejb/src/main/java/org/wildfly/httpclient/ejb/HttpInvocationHandler.java, ejb/src/test/java/org/wildfly/httpclient/ejb/EJBTestServer.java, ejb/src/test/java/org/wildfly/httpclient/ejb/EchoRemote.java, ejb/src/test/java/org/wildfly/httpclient/ejb/SimpleInvocationTestCase.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingClientMessages.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpRemoteNamingService.java, naming/src/test/java/org/wildfly/httpclient/naming/SimpleNamingOperationTestCase.java
Issues: https://issues.redhat.com/browse/WEJBHTTP-40 https://issues.redhat.com/browse/WEJBHTTP-441
Downstream PR: #35
=> [WEJBHTTP-40][WEJBHTTP-41] Support filtering of unmarshalled classes

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java
Issue: https://issues.redhat.com/browse/WEJBHTTP-48
=> [WEJBHTTP-48] Close the connection when authentication failed

transaction/src/main/java/org/wildfly/httpclient/transaction/HttpRemoteTransactionPeer.java
Issue: https://issues.redhat.com/browse/WEJBHTTP-57
@fl4via @ropalka @ochaloup would anyone please review? thanks :)
=> [WEJBHTTP-57] Use error code and initCause of XAException

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java, ejb/src/test/java/org/wildfly/httpclient/ejb/SimpleInvocationTestCase.java
Issue: https://issues.redhat.com/browse/WEJBHTTP-59
The unmarshalling of the exception is done inside the worker thread so the TCCL is not the application one there. Just passing the TCCL to the method and using a `SimpleClassResolver` with it. Test updated to check the TCCL is really used to unmarshall the exception.
The method `sendRequestInternal` receives one extra argument (the class loader). I have not created a variant to maintain the API. If you think it is necessary just let me know.
PR for master branch.
PR for 1.0: https://github.com/wildfly/wildfly-http-client/pull/64
=> [WEJBHTTP-59] EJB over HTTP getting java.lang.ClassNotFoundException to Unchecked Exception

common/src/main/java/org/wildfly/httpclient/common/HttpTargetContext.java, ejb/src/test/java/org/wildfly/httpclient/ejb/SimpleInvocationTestCase.java
Issue: https://issues.redhat.com/browse/WEJBHTTP-59
The unmarshalling of the exception is done inside the worker thread so the TCCL is not the application one there. Just passing the TCCL to the method and using a `SimpleClassResolver` with it. Test updated to check the TCCL is really used to unmarshall the exception.
The method `sendRequestInternal` receives one extra argument (the class loader). I have not created a variant to maintain the API. If you think it is necessary just let me know.
PR for branch 1.0.
PR for master: https://github.com/wildfly/wildfly-http-client/pull/63
=> [WEJBHTTP-59] (branch 1.0) EJB over HTTP getting java.lang.ClassNotFoundException to Unchecked Exception

common/pom.xml, pom.xml
Issue: https://issues.redhat.com/browse/WEJBHTTP-60
=> WEJBHTTP-60 Update project with a dependency on wildfly-elytron to use individual modules

pom.xml
Jira: https://issues.redhat.com/browse/WEJBHTTP-62
=> [WEJBHTTP-62] Upgrade XNIO to 3.8.4.Final

common/pom.xml, ejb-jakarta/pom.xml, ejb/pom.xml, pom.xml, transaction-jakarta/pom.xml, transaction/pom.xml
https://issues.redhat.com/browse/WEJBHTTP-64
=> WEJBHTTP-64 Produce a jakarta artifact for wildfly-http-client

README.md
Issue: https://issues.redhat.com/browse/WEJBHTTP-63
=> [WEJBHTTP-63] Add README to WFLY HTTP Client

common/src/main/java/org/wildfly/httpclient/common/PoolAuthenticationContext.java
Jira: https://issues.redhat.com/browse/WEJBHTTP-65
=> [WEJBHTTP-65] Do not encode URI path in digest authentication

ejb/src/main/java/org/wildfly/httpclient/ejb/EjbHttpClientMessages.java, ejb/src/test/java/org/wildfly/httpclient/ejb/EJBTestServer.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingClientMessages.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpRootContext.java, naming/src/test/java/org/wildfly/httpclient/naming/SimpleNamingOperationTestCase.java, pom.xml
Issue: https://issues.redhat.com/browse/WEJBHTTP-75
=>  WEJBHTTP-75 Problematic Language usage deprecation and replacement

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-99
=> WEJBHTTP-99 Upgrade jboss-ejb-client from 4.0.48.Final to 4.0.49.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-98
=> WEJBHTTP-98 Upgrade jboss-ejb-client from 5.0.0.Final to 5.0.1.Final

SECURITY.md
https://issues.redhat.com/browse/WEJBHTTP-102
=> [WEJBHTTP-102] Create security policy SECURITY.md

common/src/main/java/org/wildfly/httpclient/common/HttpConnectionPool.java
This PR does the following:
- reorganizes the way in which HttpConnectionPool creates new ClientConnections to the server by ensuring that the thread creating the ClientConnection and the thread executing the ConnectionListener/ErrorListener are the same. 
For more details: see https://issues.redhat.com/browse/WEJBHTTP-103
=> [WEJBHTTP-103] Adjust HttpConnectionPool to use the calling thread when invoking listeners.

CODE_OF_CONDUCT.md
https://issues.redhat.com/browse/WEJBHTTP-100
=> [WEJBHTTP-100] Add CODE_OF_CONDUCT.md

README.md
https://issues.redhat.com/browse/WEJBHTTP-101
=> [WEJBHTTP-101] Update project README

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-107
=> WEJBHTTP-107 Upgrade xnio to 3.8.8.Final

.github/workflows/ci.yml
https://issues.redhat.com/browse/WEJBHTTP-109
=> [WEJBHTTP-109] Configuring github actions

.github/dependabot.yml
https://issues.redhat.com/browse/WEJBHTTP-111
=> WEJBHTTP-111 Enable github dependabot

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-120
=> [WEJBHTTP-120] Upgrading Undertow to 2.3.10.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-121
=> [WEJBHTTP-121] Upgrading XNIO to 3.8.11.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-121
=> [WEJBHTTP-121] Upgrading XNIO to 3.8.12.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-122
=> [WEJBHTTP-122] Upgrading JBoss EJB Client to 5.0.5.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-123
=> [WEJBHTTP-123] Upgrading WildFly Common to 1.6.0.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-124
=> [WEJBHTTP-124] Upgrading WildFly Transaction Client to 3.0.2.Final

common/src/test/java/org/wildfly/httpclient/common/AcquireAffinityTestCase.java, ejb/src/main/java/org/wildfly/httpclient/ejb/HttpCancelHandler.java, ejb/src/main/java/org/wildfly/httpclient/ejb/HttpInvocationHandler.java, ejb/src/main/java/org/wildfly/httpclient/ejb/HttpSessionOpenHandler.java, ejb/src/test/java/org/wildfly/httpclient/ejb/EJBTestServer.java, naming/src/test/java/org/wildfly/httpclient/naming/ReadOnlyNamingOperationTestCase.java, naming/src/test/java/org/wildfly/httpclient/naming/SimpleNamingOperationTestCase.java, transaction/src/test/java/org/wildfly/httpclient/transaction/SimpleTransactionOperationsTestCase.java
https://issues.redhat.com/browse/WEJBHTTP-125
=> [WEJBHTTP-125] Refactoring code to don't use deprecated HttpServerExchange methods

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-126
=> [WEJBHTTP-126] Upgrading Elytron Web to 4.0.0.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-115
=> [WEJBHTTP-115] Upgrading Kohsuke metainf-services to 1.11

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-127
=> [WEJBHTTP-127] Upgrading Elytron to 2.2.2.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-128
=> [WEJBHTTP-128] Upgrading JBoss Parent to 40

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-129
=> [WEJBHTTP-129] Upgrading JBoss Modules to 2.1.2.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-130
=> [WEJBHTTP-130] Upgrading JBoss Marshalling to 2.1.3.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-131
=> [WEJBHTTP-131] Upgrading JBoss Threads to 2.4.0.Final

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-132
=> [WEJBHTTP-132] Upgrading JBoss Log Manager to 3.0.2.Final 

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-133
=> [WEJBHTTP-133] Upgrading JUnit to 4.13.2

pom.xml
https://issues.redhat.com/browse/WEJBHTTP-134
=> [WEJBHTTP-134] Upgrading AssertJ to 3.24.2

docs/pom.xml
https://issues.redhat.com/browse/WEJBHTTP-135
=> [WEJBHTTP-135] Upgrading Asciidoctor to 2.2.4

naming/src/test/java/org/wildfly/httpclient/naming/SimpleNamingOperationTestCase.java
https://issues.redhat.com/browse/WEJBHTTP-37
=> [WEJBHTTP-37] Enabling tests

naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingServerObjectResolver.java
https://issues.redhat.com/browse/WEJBHTTP-119
=> [WEJBHTTP-119] Using better way to get the server address

naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingServerObjectResolver.java
https://issues.redhat.com/browse/WEJBHTTP-119
=> [WEJBHTTP-119] Context path is configurable per connector

CODEOWNERS, CONTRIBUTING.md
Jira: https://issues.redhat.com/browse/WEJBHTTP-113
2.0 PR: #201
=> [WEJBHTTP-113] Add CODEOWNERS and CONTRIBUTING.md files

common/src/main/java/org/wildfly/httpclient/common/WildflyHttpContext.java
PR for creating patch of wildfly-http-client 1.1.17.Final for EAP 7.4.18.GA which modifies option map.
=> [WEJBHTTP-144] Add system property org.wildfly.httpclient.tcp-nodelay for ennabling/disabling Options.TCP_NODELAY

naming/src/main/java/org/wildfly/httpclient/naming/ByteOutputs.java, naming/src/main/java/org/wildfly/httpclient/naming/ClassLoaderUtils.java, naming/src/main/java/org/wildfly/httpclient/naming/ClientHandlers.java, naming/src/main/java/org/wildfly/httpclient/naming/Constants.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingContextFactory.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpNamingProviderFactory.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpRemoteNamingService.java, naming/src/main/java/org/wildfly/httpclient/naming/HttpRootContext.java, naming/src/main/java/org/wildfly/httpclient/naming/NamingConstants.java, naming/src/main/java/org/wildfly/httpclient/naming/RequestBuilder.java, naming/src/main/java/org/wildfly/httpclient/naming/RequestType.java, naming/src/main/java/org/wildfly/httpclient/naming/Serializer.java, naming/src/main/java/org/wildfly/httpclient/naming/Utils.java
https://issues.redhat.com/browse/WEJBHTTP-141
=> [WEJBHTTP-141] Second round of refactorings in JNDI part - focus on client side of the protocol

naming/src/main/java/org/wildfly/httpclient/naming/HttpRemoteNamingService.java, naming/src/main/java/org/wildfly/httpclient/naming/ServerHandlers.java
https://issues.redhat.com/browse/WEJBHTTP-151
=> [WEJBHTTP-151] Refactor JNDI server side
